Repository opengeospatial/weather-on-the-web, pull requests merged in 2018-07, with the labels that each got.

#8 Update use-cases.md
  use-cases/use-cases.md
Labels: enhancement

#15 Create Use-case-template.md
  use-cases/Use-case-template.md
Labels: enhancement

#19 typo
  README.md
Labels: invalid

#17 Create Feature Data Format proposal.md
  Specification/Feature Data Format proposal.md
Labels: Best Practice, Core Standard

#20 Create Feature-Data-Demonstrator.md
  engineering/Feature-Data-Demonstrator.md
Labels: Best Practice

#22 Create get-parameters-for-point-across-timeseries.md
  use-cases/get-parameters-for-point-across-timeseries.md
Labels: Use case
